version: '3'

networks:
  glastopf_local:

services:

# Glastopf service
  glastopf:
    build: .
    container_name: glastopf
    restart: always
    networks:
     - glastopf_local
    ports:
     - "80:80"
    image: "ardikabs/glastopf:1.0"
    volumes:
     - /data/glastopf/db:/opt/glastopf/db
     - /data/glastopf/log:/opt/glastopf/log