version: '3'

services:
  broker:
    container_name: mqtt-broker
    restart: always
    image: "eclipse-mosquitto"
    expose:
      - "1883/tcp"
      - "9001/tcp"
    volumes:
      - ${SERVER_DIR}/docker/mqtt-broker/config:/mosquitto/config/
      - ${SERVER_DIR}/docker/mqtt-broker/data:/mosquitto/data/
      - ${SERVER_DIR}/docker/mqtt-broker/log:/mosquitto/log/
      - ${SERVER_DIR}/docker/mqtt-broker/auth:/mosquitto/auth/

  mongodb:
    container_name: mongodb
    restart: always
    image: "mongo"
    expose:
      - "27017/tcp"
    volumes:
      - /data/db:/data/db

  collector:
    build: ./mqtt-subs
    container_name: collector
    restart: always
    image: "ardikabs/collector"
    links:
      - mongodb
      - broker
    depends_on:
      - mongodb
      - broker
    volumes:
      - ${SERVER_DIR}/docker/mqtt-subs/collector:/collector

  reverseproxy:
    build: ./nginx
    container_name: reverseproxy
    restart: always
    image: "ardikabs/reverse-proxy"
    links:
      - serverapp
      - mongodb
      - fluentd-master
      - fluentd-node1
      - fluentd-node2
    depends_on:
      - mongodb
      - serverapp
      - fluentd-master
      - fluentd-node1
      - fluentd-node2

    ports:
      - "80:80"
      - "27020:27020/tcp"
      - "24224:24224/tcp"
      - "24224:24224/udp"
    volumes:
      - ${SERVER_DIR}/docker/nginx/log:/var/log/nginx/

  serverapp:
    build: ./server
    container_name: serverapp
    restart: always
    image: "ardikabs/fipro-server"
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - ${SERVER_DIR}/docker/server/project:/project
  

  fluentd:
    container_name: aggregator-master
    restart: always
    image: "ardikabs/fluentd"
    depends_on:
      - broker
      - collector
    expose:
      - "24224/tcp"
      - "24224/udp"
    volumes:
      - ${SERVER_DIR}/docker/fluentd/conf:/fluentd/etc

  fluentd-node1:
    container_name: aggregator-node1
    restart: always
    image: "ardikabs/fluentd"
    depends_on:
      - broker
      - collector
    expose:
      - "24224/tcp"
      - "24224/udp"
    volumes:
      - ${SERVER_DIR}/docker/fluentd/conf-node1:/fluentd/etc

  fluentd-node2:
    container_name: aggregator-node2
    restart: always
    image: "ardikabs/fluentd"
    depends_on:
      - broker
      - collector
    expose:
      - "24224/tcp"
      - "24224/udp"
    volumes:
      - ${SERVER_DIR}/docker/fluentd/conf-node2:/fluentd/etc
  