version: '3'

services:
  broker:
    container_name: mqtt-broker
    restart: always
    image: "eclipse-mosquitto"
    ports:
      - "1883/tcp"
      - "9001/tcp"
    volumes:
      - /var/fipro-core/docker/mqtt-broker/config:/mosquitto/config/
      - /var/fipro-core/docker/mqtt-broker/data:/mosquitto/data/
      - /var/fipro-core/docker/mqtt-broker/log:/mosquitto/log/
      - /var/fipro-core/docker/mqtt-broker/auth:/mosquitto/auth/

  mongodb:
    container_name: mongodb
    restart: always
    image: "mongo"
    ports:
      - 27017/tcp
    volumes:
      - /data/db:/data/db

  collector:
    build: ./mqtt-subs
    container_name: collector
    restart: always
    image: "ardikabs/collector"
    links:
      - mongodb
      - mqtt-broker
    depends_on:
      - mongodb
      - broker
    volumes:
      - /var/fipro-core/docker/mqtt-subs/collector:/collector

  reverseproxy:
    build: ./nginx
    container_name: reverse-proxy
    restart: always
    image: "ardikabs/reverse-proxy"
    links:
      - serverapp
      - mongodb
      - fluentd
    depends_on:
      - serverapp
      - mongodb
      - fluentd
    ports:
      - "80:80"
      - "24224:24224"
      - "27017:27017"
    volumes:
      - /var/fipro-core/docker/nginx/log:/var/log/nginx/

  serverapp:
    build: ./server
    container_name: serverapp
    restart: always
    image: "ardikabs/fipro-server"
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - /var/fipro-core/docker/server/project:/project
  

  fluentd:
    container_name: aggregator
    restart: always
    image: "ardikabs/fluentd"
    ports:
      - 24224/tcp
    depends_on:
      - broker
      - collector
    volumes:
      - /var/fipro-core/docker/fluentd/conf:/fluentd/etc
  