version: '3'

services:
  broker:
    container_name: mqtt-broker
    restart: always
    image: "eclipse-mosquitto"
    expose:
      - "1883/tcp"
      - "9001/tcp"
    volumes:
      - /var/fipro-core/docker/mqtt-broker/config:/mosquitto/config/
      - /var/fipro-core/docker/mqtt-broker/data:/mosquitto/data/
      - /var/fipro-core/docker/mqtt-broker/log:/mosquitto/log/
      - /var/fipro-core/docker/mqtt-broker/auth:/mosquitto/auth/

  mongodb:
    container_name: mongodb
    restart: always
    image: "mongo"
    expose:
      - "27017/tcp"
    volumes:
      - /data/db:/data/db

  collector:
    build: ./mqtt-subs
    container_name: collector
    restart: always
    image: "ardikabs/collector"
    links:
      - mongodb
      - broker
    depends_on:
      - mongodb
      - broker
    volumes:
      - /var/fipro-core/docker/mqtt-subs/collector:/collector

  reverseproxy:
    build: ./nginx
    container_name: reverseproxy
    restart: always
    image: "ardikabs/reverse-proxy"
    links:
      - serverapp
      - mongodb
      - fluentd-master
      - fluentd-cluster1
      - fluentd-cluster2
    depends_on:
      - mongodb
      - serverapp
      - fluentd-master
      - fluentd-cluster1
      - fluentd-cluster2

    ports:
      - "80:80"
      - "27020:27020/tcp"
      - "24224/tcp:24224/tcp"
      - "24224/udp:24224/udp"
    volumes:
      - /var/fipro-core/docker/nginx/log:/var/log/nginx/

  serverapp:
    build: ./server
    container_name: serverapp
    restart: always
    image: "ardikabs/fipro-server"
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - /var/fipro-core/docker/server/project:/project
  

  fluentd-master:
    container_name: aggregator-master
    restart: always
    image: "ardikabs/fluentd"
    depends_on:
      - broker
      - collector
    expose:
      - "24224/tcp"
      - "24224/udp"
    volumes:
      - /var/fipro-core/docker/fluentd/conf:/fluentd/etc

  fluentd-cluster1:
    container_name: aggregator-cluster1
    restart: always
    image: "ardikabs/fluentd"
    depends_on:
      - broker
      - collector
    expose:
      - "24224/tcp"
      - "24224/udp"
    volumes:
      - /var/fipro-core/docker/fluentd/conf-cluster1:/fluentd/etc

  fluentd-cluster2:
    container_name: aggregator-cluster2
    restart: always
    image: "ardikabs/fluentd"
    depends_on:
      - broker
      - collector
    expose:
      - "24224/tcp"
      - "24224/udp"
    volumes:
      - /var/fipro-core/docker/fluentd/conf-cluster2:/fluentd/etc
  