"""empty message

Revision ID: 700e569f3965
Revises: ad255b1413d6
Create Date: 2018-06-26 21:20:25.955871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700e569f3965'
down_revision = 'ad255b1413d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('old_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_id', sa.String(length=20), nullable=True),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('ipaddr', sa.String(length=64), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('condition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('old_agents')
    # ### end Alembic commands ###
